# -*- coding: utf-8 -*-
"""app_final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOH5BUSPdV8XeWQR7DkOlLUto0gsFfrC
"""



# ============================================================
# Run this whole thing as ONE Colab cell.
# It will pause partway through to let you upload app.py
# and the corrected CSV — just follow the upload prompts.
# ============================================================

# 1. Install dependencies
!pip install -q streamlit streamlit-folium folium plotly pyngrok

import os, time
from google.colab import files
from pyngrok import ngrok

os.makedirs("data", exist_ok=True)

# 2. Upload app.py (renamed to exactly "app.py" no matter what it was called)
print("Upload app.py:")
uploaded = files.upload()
app_fname = list(uploaded.keys())[0]
if app_fname != "app.py":
    os.rename(app_fname, "app.py")

# 3. Upload the corrected CSV
print("Now upload hydroai_final_scored.csv (the corrected one):")
uploaded_data = files.upload()
csv_fname = list(uploaded_data.keys())[0]
os.rename(csv_fname, "data/hydroai_final_scored.csv")

print("Files ready:", os.listdir("."), "| data/:", os.listdir("data"))

# 4. Set your ngrok auth token (paste it below)
NGROK_AUTH_TOKEN = "3Et5fZQ2h2TS9t19k6WyfKkY7F8_YhhMgzWmjv8H82LBg8G4"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# 5. Kill any existing tunnels/streamlit from previous runs, then start fresh
ngrok.kill()
!pkill -f streamlit
time.sleep(2)

!streamlit run app.py --server.port 8501 &>/content/logs.txt &
time.sleep(6)
!tail -n 20 /content/logs.txt

# 6. Open the tunnel
public_url = ngrok.connect(8501)
print("\nYour app is live at:", public_url)